name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      # ✅ STEP: GENERATE APP ICON & SPLASH SCREEN
      # Intha step thaan unga logo-ah app icon-ah mathum
      - name: Generate App Assets
        working-directory: frontend
        run: |
          npx @capacitor/assets generate --android --icon-path assets/logo.png --splash-path assets/logo.png

      - name: Build Web Project
        working-directory: frontend
        run: npm run build

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Sync Capacitor
        working-directory: frontend
        run: npx cap sync

      - name: Build APK
        working-directory: frontend/android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LifeDrop-App
          path: frontend/android/app/build/outputs/apk/debug/app-debug.apk